// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cache struct {
	Key     string
	Data    []byte
	Expires pgtype.Timestamptz
}
