// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOld = `-- name: DeleteOld :exec
DELETE FROM cache WHERE expires <= $1
`

func (q *Queries) DeleteOld(ctx context.Context, expires pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOld, expires)
	return err
}

const getCache = `-- name: GetCache :one
SELECT data, expires FROM cache
WHERE key = $1 LIMIT 1
`

type GetCacheRow struct {
	Data    []byte
	Expires pgtype.Timestamptz
}

// Cache queries using hstore for key-value data storage
func (q *Queries) GetCache(ctx context.Context, key string) (GetCacheRow, error) {
	row := q.db.QueryRow(ctx, getCache, key)
	var i GetCacheRow
	err := row.Scan(&i.Data, &i.Expires)
	return i, err
}

const insertCache = `-- name: InsertCache :exec
INSERT INTO cache (key, data, expires)
VALUES ($1, $2, $3)
ON CONFLICT(key) DO UPDATE SET
    data = excluded.data,
    expires = excluded.expires
`

type InsertCacheParams struct {
	Key     string
	Data    []byte
	Expires pgtype.Timestamptz
}

func (q *Queries) InsertCache(ctx context.Context, arg InsertCacheParams) error {
	_, err := q.db.Exec(ctx, insertCache, arg.Key, arg.Data, arg.Expires)
	return err
}
